//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaMVC.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Contato
    {
        public Contato()
        {
            this.Telefone = new HashSet<Telefone>();
        }
        
        [DisplayName("Nome")]
        [Required(ErrorMessage = "Informe um nome")]
        public string nome { get; set; }

        public int idContato { get; set; }
        
        [DisplayName("Empresa")]
        public string empresa { get; set; }
    
        public virtual ICollection<Telefone> Telefone { get; set; }
    }
}
