//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
    
    public partial class Telefone
    {
        public int idContato { get; set; }
        
        [Key]
        public int idTelefone { get; set; }
        
        [DisplayName("Telefone")]
        public string fone { get; set; }
    
        public virtual Contato Contato { get; set; }
    }
}
